// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANWNzL3IiX2IiX_wOusx_f00yds-NUvrA',
    appId: '1:67437776736:web:69b90d1c1fd9501a3ed805',
    messagingSenderId: '67437776736',
    projectId: 'women-safety-app-7373c',
    authDomain: 'women-safety-app-7373c.firebaseapp.com',
    storageBucket: 'women-safety-app-7373c.firebasestorage.app',
    measurementId: 'G-JERPLCTPW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoI5T6oHPtsx_OMDqrp2MCeNovXGY9pWM',
    appId: '1:67437776736:android:bf1cb9ee4d3b5cd63ed805',
    messagingSenderId: '67437776736',
    projectId: 'women-safety-app-7373c',
    storageBucket: 'women-safety-app-7373c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1oPYg1ayFh_mE2g07z1dyHV2Zp4O97Fc',
    appId: '1:67437776736:ios:924f7e7dd41c0f853ed805',
    messagingSenderId: '67437776736',
    projectId: 'women-safety-app-7373c',
    storageBucket: 'women-safety-app-7373c.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1oPYg1ayFh_mE2g07z1dyHV2Zp4O97Fc',
    appId: '1:67437776736:ios:924f7e7dd41c0f853ed805',
    messagingSenderId: '67437776736',
    projectId: 'women-safety-app-7373c',
    storageBucket: 'women-safety-app-7373c.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANWNzL3IiX2IiX_wOusx_f00yds-NUvrA',
    appId: '1:67437776736:web:2edac9efdb8d604a3ed805',
    messagingSenderId: '67437776736',
    projectId: 'women-safety-app-7373c',
    authDomain: 'women-safety-app-7373c.firebaseapp.com',
    storageBucket: 'women-safety-app-7373c.firebasestorage.app',
    measurementId: 'G-F8M6QWLV8R',
  );
}
